<?php
	// THIS IS THE CONFIGURATION FILE WITH GLOBAL VARIABLES AND SESSION DATA
	session_start();
	
	$mailAdmin = ""; // Replace this with the email you wish emails generated by the system to be from. EX. yourName@yourHost.com
	$globalAdmin = "admin"; // DO NOT CHANGE
	$webAddress = ""; // Website URL
	$dbhost = ""; // Do not change (in almost all cases)
	$dbuser = ""; // What you want your database username to be (install.php will create it)
	$dbpass = ""; // What you want your database password to be (install.php will create it)
	$dbname = ""; // What you want the database to be called (install.php will create it)
	
?>
	